# Generated by Django 5.2.6 on 2025-09-13 15:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_assets', models.JSONField()),
                ('interval', models.CharField(max_length=10)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2010, 1, 1, 0, 0))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2025, 9, 12, 15, 16, 36, 13945))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
