# Generated by Django 5.2.6 on 2025-09-13 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 12, 0, 0)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='interval',
            field=models.CharField(choices=[('1m', '1 minute'), ('2m', '2 minutes'), ('5m', '5 minutes'), ('15m', '15 minutes'), ('30m', '30 minutes'), ('60m', '1 hour'), ('90m', '90 minutes'), ('1d', 'Daily'), ('5d', 'Every 5 days'), ('1wk', 'Weekly'), ('1mo', 'Monthly'), ('3mo', 'Quarterly')], max_length=5),
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='selected_assets',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='selected_assets',
            field=models.ManyToManyField(to='portfolio.asset'),
        ),
    ]
